version: '3.8'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./app/web
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"


  # api:
    # container_name: api
    # build:
    #   context: .
    #   dockerfile: ./apps/api/Dockerfile
    # restart: always
    # ports:
    #   - "3001:3001"
    # networks:
    # - app_network

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  redis:
    image: redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname


volumes:
  postgres_data:
  redis_data:
